# trusty beta image has jdk8, gcc4.8.4
dist: trusty
sudo: required
# xcode8 has jdk8
osx_image: xcode8.3
# Not technically required but suppresses 'Ruby' in Job status message.
language: java

os:
  - linux
#  - osx

env:
  - V=0.21.0
addons:
  apt:
    packages:
      - jq

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      OS=darwin
    else
      sysctl kernel.unprivileged_userns_clone=1
      OS=linux
    fi
    URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-${OS}-x86_64.sh"
    wget -O install.sh "${URL}"
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh

script:
  - |
    bazel \
      --output_base=$HOME/.cache/bazel \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      test \
      --config=ci \
      --experimental_repository_cache="$HOME/.bazel_repository_cache" \
      --local_resources=400,1,1.0 \
      //...

  #run HOW TO steps
  - bazel run //docker:coordinator
  - bazel run //docker:layers_calculator
  - cd docs/private_tangle
  - cat config.example.json| jq '.tick = 5000' > config.json
  - cp snapshot.example.txt snapshot.txt
  - ./01_calculate_layers.sh
  - ./02_run_iri.sh &
  - |
    until [ `docker ps | grep iri | cut -f1 -d\ ` ]; do
    sleep 1;
    done
  - sleep 20
  - ./03_run_coordinator.sh -bootstrap -broadcast &
  - sleep 120
  - docker kill $(docker ps | grep compass | cut -f1 -d\ )
  - docker kill $(docker ps | grep iri | cut -f1 -d\ )

notifications:
  email: false
